### ISSUE TITLE
Add method to StateInLocation

### ISSUE THREAD

**Issue by dfcaporale** [JuliaReach/ReachabilityAnalysis.jl#279] opened 2020-07-14 17:27 UTC
(Related to https://github.com/JuliaReach/ARCH2020_NLN_RE/tree/master/models/Spacecraft)

`prob = spacecraft()`

InitialValueProblem{HybridSystem{LightAutomaton{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},LightGraphs.SimpleGraphs.SimpleEdge{Int64}},ConstrainedBlackBoxContinuousSystem,ConstrainedIdentityMap,AutonomousSwitching,Array{ConstrainedBlackBoxContinuousSystem,1},Array{ConstrainedIdentityMap,1},Array{AutonomousSwitching,1}},Array{Tuple{Int64,Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}},1}}(Hybrid System with automaton LightAutomaton{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},LightGraphs.SimpleGraphs.SimpleEdge{Int64}}({3, 3} directed simple Int64 graph, Dict{LightGraphs.SimpleGraphs.SimpleEdge{Int64},Dict{Int64,Int64}}(Edge 2 => 3 => Dict(3 => 3),Edge 1 => 2 => Dict(1 => 1),Edge 1 => 3 => Dict(2 => 2)), 3, 3), Tuple{Int64,Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}}[(1, Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([-900.0, -400.0, 0.0, 0.0, 0.0], [25.0, 25.0, 0.0, 0.0, 0.0]))])

`sol = solve_spacecraft(prob; k=25, s=missing)`

**MethodError: Cannot `convert` an object of type 
  ReachabilityAnalysis.StateInLocation{HPolytope{Float64{},Array{Float64,1}},Int64{}} to an object of type 
  ReachabilityAnalysis.StateInLocation{HPolytope{Float64{},LazySets.Arrays.SingleEntryVector{Float64}},Int64{}}**
Closest candidates are:
  convert(::Type{var"#s28"} where var"#s28"<:Union{Number, T}, !Matched::MultivariatePolynomials.AbstractPolynomialLike{T}) where T at C:\Users\danie\.julia\packages\MultivariatePolynomials\fixWm\src\conversion.jl:65
  convert(::Type{ReachabilityAnalysis.StateInLocation{ST,M}}, !Matched::ReachabilityAnalysis.StateInLocation{WT,M}) where {ST, WT<:ST, M} at C:\Users\danie\.julia\dev\ReachabilityAnalysis\src\Hybrid\waiting_list.jl:15
  convert(::Type{T}, !Matched::Intervals.Interval{T,L,R} where R<:Intervals.Bound where L<:Intervals.Bound) where T at C:\Users\danie\.julia\packages\Intervals\9S2ok\src\interval.jl:194
  ...

Stacktrace:
 [1] push!(::Array{ReachabilityAnalysis.StateInLocation{HPolytope{Float64,LazySets.Arrays.SingleEntryVector{Float64}},Int64},1}, ::ReachabilityAnalysis.StateInLocation{HPolytope{Float64,Array{Float64,1}},Int64}) at .\array.jl:936
 [2] push! at C:\Users\danie\.julia\dev\ReachabilityAnalysis\src\Hybrid\waiting_list.jl:74 [inlined]
 [3] convert(::Type{ReachabilityAnalysis.WaitingList{Float64,HPolytope{Float64,LazySets.Arrays.SingleEntryVector{Float64}},Int64,ReachabilityAnalysis.StateInLocation{HPolytope{Float64,LazySets.Arrays.SingleEntryVector{Float64}},Int64}}}, ::Array{Tuple{Int64,HPolytope{Float64,Array{Float64,1}}},1}) at C:\Users\danie\.julia\dev\ReachabilityAnalysis\src\Hybrid\waiting_list.jl:103
 [4] _distribute(::InitialValueProblem{HybridSystem{LightAutomaton{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},LightGraphs.SimpleGraphs.SimpleEdge{Int64}},ConstrainedBlackBoxContinuousSystem,ConstrainedIdentityMap,AutonomousSwitching,Array{ConstrainedBlackBoxContinuousSystem,1},Array{ConstrainedIdentityMap,1},Array{AutonomousSwitching,1}},Array{Tuple{Int64,Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}},1}}; intersection_method::TemplateHullIntersection{Float64,LazySets.Arrays.SingleEntryVector{Float64},BoxDirections{Float64,LazySets.Arrays.SingleEntryVector{Float64}}}, check_invariant::Bool, intersect_invariant::Bool) at C:\Users\danie\.julia\dev\ReachabilityAnalysis\src\Hybrid\solve.jl:293
 [5] solve(::InitialValueProblem{HybridSystem{LightAutomaton{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},LightGraphs.SimpleGraphs.SimpleEdge{Int64}},ConstrainedBlackBoxContinuousSystem,ConstrainedIdentityMap,AutonomousSwitching,Array{ConstrainedBlackBoxContinuousSystem,1},Array{ConstrainedIdentityMap,1},Array{AutonomousSwitching,1}},Array{Tuple{Int64,Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}},1}}; max_jumps::Int64, intersection_method::TemplateHullIntersection{Float64,LazySets.Arrays.SingleEntryVector{Float64},BoxDirections{Float64,LazySets.Arrays.SingleEntryVector{Float64}}}, clustering_method::LazyClustering{Int64}, check_invariant_initial_states::Bool, intersect_invariant_initial_states::Bool, intersection_source_invariant_method::FallbackIntersection, first_mode_representative::Bool, intersect_source_invariant::Bool, disjointness_method::BoxEnclosure, kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:tspan, :alg),Tuple{Tuple{Float64,Float64},TMJets{Float64,BoxEnclosure}}}}) at C:\Users\danie\.julia\dev\ReachabilityAnalysis\src\Hybrid\solve.jl:21
 [6] solve_spacecraft(::InitialValueProblem{HybridSystem{LightAutomaton{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},LightGraphs.SimpleGraphs.SimpleEdge{Int64}},ConstrainedBlackBoxContinuousSystem,ConstrainedIdentityMap,AutonomousSwitching,Array{ConstrainedBlackBoxContinuousSystem,1},Array{ConstrainedIdentityMap,1},Array{AutonomousSwitching,1}},Array{Tuple{Int64,Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}},1}}; k::Int64, s::Missing) at .\In[5]:6
 [7] top-level scope at In[10]:1

**Comment by mforets** [comment] 2020-07-14 19:22
[PR#280](https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/280) may fix it (i didn't try). the problem is that the waiting list type was set to match with that of the intersection method being used (which is most often correct because the waiting list is fed with whatever is returned by discrete `apply` map). however, for the very initial state there is no such intersection, hence the problem.

**Comment by mforets** [comment] 2020-07-14 20:24
fixed by https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/280

**Closed by mforets** 2020-07-14 20:24 UTC

**Comment by dfcaporale** [comment] 2020-07-15 12:56
Excellent!
